version: "3"
services:
  sqlite_db:
    image: sqlite:latest
    build:
      context: sqlite_docker
      dockerfile: ./Dockerfile
    ports:
      - "8191:8191"
    volumes:
      - type: bind
        source: ./database
        target: /db
    stdin_open: true # docker run -i
    tty: true # docker run -t
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
    stdin_open: true # docker run -i
    tty: true # docker run -t
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - type: bind
        source: ./redis_data
        target: /data
